version: '3.8'

services:
  movie-rating-prediction:
    build: .
    container_name: movie-rating-prediction
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped